version: '3.3'

services: 
    client:
        container_name: user-client
        image: user-client
        build: 
            context: client
        depends_on: 
            - server
        volumes: 
            - ./client:/app/client
            - /app/client/node_modules
        ports: 
            - "3001:3000"
        environment:
            - CHOKIDAR_USEPOLLING=true

    server:
        container_name: user-server
        image: user-server
        build: 
            context: server
        depends_on:
            - db
        volumes: 
            - ./server/flaskkr:/app/server/flaskkr
            - ./server/db.yaml:/app/server/db.yaml
            - ./wait-for:/wait-for
        ports:
            - "5000:5000"
        environment: 
            FLASK_ENV: development
        command: sh -c "sleep 10s&&flask run"

    local-nginx:
        container_name: local-nginx
        image: local-nginx
        build: 
            context: local-nginx
        ports:
            - "80:80"
        volumes:
            - ./local-nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - server
            - client
        restart: unless-stopped
        command: "supervisord -n"

    db:
        container_name: user-database
        image: mysql:8.0
        volumes: 
            - ./server/mysql-init-scripts:/docker-entrypoint-initdb.d
            - ./mysqldata:/var/lib/mysql
        cap_add:
            - SYS_NICE
        ports: 
            - "3306:3306"
        environment: 
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=user_info
